project:
  type: website

website:
  title: "MKZ Blog"
  description: "Offizieler Blog des MKZ"
  navbar:
    right:
      - text: Blog
        href: blog.html
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

execute:
  freeze: auto
